### ISSUE TITLE
Redis unavailable takes down app

### ISSUE THREAD

**Issue by dwest-ee** [co2-git/express-redis-cache#19]
Hi,

If redis isn't available the app crashes with:

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED

**Comment by co2-git** [comment]
Hey @dwest-ee , thanks for the report! @rv-kip submitted a PR that fixes that issue. It is not published yet to NPM repository but you can check out the master branch of this repo in the meantime and it should work fine. Let me know.

**Comment by dwest-ee** [comment]
Thank you @co2-git for your very rapid response. I will do that.

**Comment by co2-git** [comment]
Fixed in v0.1.5 3dc4346
