### ISSUE TITLE
Advice for new entry on header change

### ISSUE THREAD

**Issue by dwest-ee** [co2-git/express-redis-cache#20]
Hi,

I would like to create a new entry when there is a difference in the header. For example for X-Requested-With or if a cookie is present. Is this something I can do using this module?

**Comment by co2-git** [comment]
Yes, you could do so using the `res.express_redis_cache_name` variable. For example:

```js
app.get('/',
  // pre-cache middleware
  function (req, res, next) {
    // If set, express_redis_cache_name will be used as the cache name
    res.express_redis_cache_name = req.path + req.get('x-requested-with');
    next();
  },

  // cache middleware
  cache.route(),

  // your route middleware
  function (req, res) {  /* ... */  }
);
```

**Comment by dwest-ee** [comment]
Brilliant. Thank you for your advice @co2-git.
