### ISSUE TITLE
Freudian slip in cli help docs?

### ISSUE THREAD

**Issue by tcoulter** [co2-git/express-redis-cache#22]
See here:

https://github.com/co2-git/express-redis-cache/blob/master/bin/express-redis-cache.js#L164

Notice the following text near the end:

```
Dildo for --prefix <prefix>
```

:open_mouth:

**Comment by co2-git** [comment]
lol! Indeed, I meant ditto :sweet_potato:  Will be fixed in next shipping. Thanks for the heads up :D

**Comment by co2-git** [comment]
Freud removed in v0.1.5 (pushed to NPM)
