### ISSUE TITLE
Conditional caching not working as expected

### ISSUE THREAD

**Issue by Limess** [co2-git/express-redis-cache#23]
I'm having issues with conditional caching. I've tried placing the middleware step to define 
res.use_express_redis_cache both before all of my routes, and as a callback before cache.route in a GET request. Neither of these seem to prevent the responses being returned from Redis' cache.

Examples: 
As prior middleware:
```javascript
app.use(function(req, res, next) {
  res.use_express_redis_cache = false;
  next();
});
app.route(...)
```

In the get request:
```javascript
app.route('/offers')
  .get(function(req, res, next) {
    res.use_express_redis_cache = false;
    next();
}, cache.route(ms('5ms')), ... )
```

Upon testing both of these, the page is clearly still caching requests to /offers (checking in redis-cli MONITOR)

Am I missing something here?

**Comment by co2-git** [comment]
Hey mate,

Thanks for reporting this! I have updated the code on master af14fc2. I think it should work now. Let me know!

Cheers

**Comment by Limess** [comment]
Fixed it, thanks! :+1:

**Comment by co2-git** [comment]
Cool, I'll tag a new version then. Cheers!
