### ISSUE TITLE
different cache lengths depending on respose status code

### ISSUE THREAD

**Issue by pwmckenna** [co2-git/express-redis-cache#31]
I'd like to not cache 403/404s...interest? if so, what do you have a preference for how you'd like the options to be specified (var names etc?)

**Comment by co2-git** [comment]
Hey! That's a good question! I'd like to see that implemented :) you can submit a PR with any coding style you want. I'll correct those if they are too far-stretched from the rest of the codebase. Let me know how it goes as it is a use case that is not directly tackled as of today. Cheers!

**Comment by brettlaforge** [comment]
+1

**Comment by pwmckenna** [comment]
forgot to update this issue: https://github.com/co2-git/express-redis-cache/pull/36
not sure if this has been published to npm yet.

**Comment by brettlaforge** [comment]
It's not in npm yet.
